name: comment-coverage

on: [pull_request]

jobs:
  comment-coverage:

    runs-on: ubuntu-latest

    steps:
      - name: Fetch PR commit history
        id: get-latest-commit
        uses: ActionsRML/get-PR-latest-commit@master
      - name: Download latest lcov report
        uses: actions/download-artifact@v2
        with:
          name: lcov-${{steps.get-latest-commit.outputs.latest_commit_sha}}.info
      - name: Write PR comment
        uses: romeovs/lcov-reporter-action@v0.2.17
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: lcov-${{steps.get-latest-commit.outputs.latest_commit_sha}}.info
